
services:

   db:
    image: postgres:17

    container_name: postgres.db

    restart: always

    networks:
      - shared_db

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

      - ./database/seed:/seed

    
   web:
    build: .

    container_name: flask-app

    restart: always

    networks:
      - shared_db

    env_file:
      - .env

    ports:
      - "5000:5000"

    depends_on:
      - db
    
    develop:
      watch:

        - action: sync
          path: .
          target: /app

        - action: rebuild
          path: requirement.txt




volumes:
  postgres_data:

networks:
   shared_db:
      name: shared_db