version: '3.9'

services:

   db:
    image: postgres:lastest

    container_name: postgres.db

    restart: always

    env_file:
      - .env

    environment:
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_PASSWORD:${DB_PASSWORD}
      - POSTGRES_DB:${DB_NAME}
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

      - .database/seed:/seed

    
   web:
    build: .

    container_name: flask-app

    restart: always

    env_file:
      - .env

    ports:
      -"5000:5000"

    depends_on:
      - db
    
    develop:
      watch:

        - action: sync
          path: .
          target: /add

        - action: rebuild
          path: requirement.txt




volumes:
  postgres_data: